export interface Country {
  value: string;
  label: string;
  code: string;
}

export const COUNTRIES: Country[] = [
  { value: "Afghanistan", label: "Afghanistan", code: "AF" },
  { value: "Albania", label: "Albania", code: "AL" },
  { value: "Algeria", label: "Algeria", code: "DZ" },
  { value: "American Samoa", label: "American Samoa", code: "AS" },
  { value: "Andorra", label: "Andorra", code: "AD" },
  { value: "Angola", label: "Angola", code: "AO" },
  { value: "Anguilla", label: "Anguilla", code: "AI" },
  { value: "Antarctica", label: "Antarctica", code: "AQ" },
  { value: "Antigua and Barbuda", label: "Antigua and Barbuda", code: "AG" },
  { value: "Argentina", label: "Argentina", code: "AR" },
  { value: "Armenia", label: "Armenia", code: "AM" },
  { value: "Aruba", label: "Aruba", code: "AW" },
  { value: "Australia", label: "Australia", code: "AU" },
  { value: "Austria", label: "Austria", code: "AT" },
  { value: "Azerbaijan", label: "Azerbaijan", code: "AZ" },
  { value: "Bahamas", label: "Bahamas", code: "BS" },
  { value: "Bahrain", label: "Bahrain", code: "BH" },
  { value: "Bangladesh", label: "Bangladesh", code: "BD" },
  { value: "Barbados", label: "Barbados", code: "BB" },
  { value: "Belarus", label: "Belarus", code: "BY" },
  { value: "Belgium", label: "Belgium", code: "BE" },
  { value: "Belize", label: "Belize", code: "BZ" },
  { value: "Benin", label: "Benin", code: "BJ" },
  { value: "Bermuda", label: "Bermuda", code: "BM" },
  { value: "Bhutan", label: "Bhutan", code: "BT" },

  { value: "Bolivia", label: "Bolivia", code: "BO" },
  {
    value: "Bosnia and Herzegovina",
    label: "Bosnia and Herzegovina",
    code: "BA",
  },
  { value: "Botswana", label: "Botswana", code: "BW" },
  { value: "Brazil", label: "Brazil", code: "BR" },
  {
    value: "British Indian Ocean Territory",
    label: "British Indian Ocean Territory",
    code: "IO",
  },
  {
    value: "British Virgin Islands",
    label: "British Virgin Islands",
    code: "VG",
  },
  { value: "Brunei", label: "Brunei", code: "BN" },
  { value: "Bulgaria", label: "Bulgaria", code: "BG" },
  { value: "Burkina Faso", label: "Burkina Faso", code: "BF" },
  { value: "Burundi", label: "Burundi", code: "BI" },
  { value: "Cambodia", label: "Cambodia", code: "KH" },
  { value: "Cameroon", label: "Cameroon", code: "CM" },
  { value: "Canada", label: "Canada", code: "CA" },
  { value: "Cape Verde", label: "Cape Verde", code: "CV" },
  { value: "Cayman Islands", label: "Cayman Islands", code: "KY" },
  {
    value: "Central African Republic",
    label: "Central African Republic",
    code: "CF",
  },
  { value: "Chad", label: "Chad", code: "TD" },
  { value: "Chile", label: "Chile", code: "CL" },
  { value: "China", label: "China", code: "CN" },
  { value: "Christmas Island", label: "Christmas Island", code: "CX" },
  { value: "Cocos Islands", label: "Cocos Islands", code: "CC" },
  { value: "Colombia", label: "Colombia", code: "CO" },
  { value: "Comoros", label: "Comoros", code: "KM" },
  { value: "Cook Islands", label: "Cook Islands", code: "CK" },
  { value: "Costa Rica", label: "Costa Rica", code: "CR" },
  { value: "Croatia", label: "Croatia", code: "HR" },
  { value: "Cuba", label: "Cuba", code: "CU" },
  { value: "Curaçao", label: "Curaçao", code: "CW" },
  { value: "Cyprus", label: "Cyprus", code: "CY" },
  { value: "Czech Republic", label: "Czech Republic", code: "CZ" },
  {
    value: "Democratic Republic of the Congo",
    label: "Democratic Republic of the Congo",
    code: "CD",
  },
  { value: "Denmark", label: "Denmark", code: "DK" },
  { value: "Djibouti", label: "Djibouti", code: "DJ" },
  { value: "Dominica", label: "Dominica", code: "DM" },
  { value: "Dominican Republic", label: "Dominican Republic", code: "DO" },
  { value: "East Timor", label: "East Timor", code: "TL" },
  { value: "Ecuador", label: "Ecuador", code: "EC" },
  { value: "Egypt", label: "Egypt", code: "EG" },
  { value: "El Salvador", label: "El Salvador", code: "SV" },
  { value: "Equatorial Guinea", label: "Equatorial Guinea", code: "GQ" },
  { value: "Eritrea", label: "Eritrea", code: "ER" },
  { value: "Estonia", label: "Estonia", code: "EE" },
  { value: "Ethiopia", label: "Ethiopia", code: "ET" },
  { value: "Finland", label: "Finland", code: "FI" },
  { value: "France", label: "France", code: "FR" },
  { value: "Germany", label: "Germany", code: "DE" },
  { value: "Ghana", label: "Ghana", code: "GH" },
  { value: "Greece", label: "Greece", code: "GR" },
  { value: "Greenland", label: "Greenland", code: "GL" },
  { value: "Hong Kong", label: "Hong Kong", code: "HK" },
  { value: "Hungary", label: "Hungary", code: "HU" },
  { value: "Iceland", label: "Iceland", code: "IS" },
  { value: "India", label: "India", code: "IN" },
  { value: "Indonesia", label: "Indonesia", code: "ID" },
  { value: "Iran", label: "Iran", code: "IR" },
  { value: "Iraq", label: "Iraq", code: "IQ" },
  { value: "Ireland", label: "Ireland", code: "IE" },
  { value: "Israel", label: "Israel", code: "IL" },
  { value: "Italy", label: "Italy", code: "IT" },
  { value: "Japan", label: "Japan", code: "JP" },
  { value: "Kenya", label: "Kenya", code: "KE" },
  { value: "South Africa", label: "South Africa", code: "ZA" },
  { value: "South Korea", label: "South Korea", code: "KR" },
  { value: "Spain", label: "Spain", code: "ES" },
  { value: "Sri Lanka", label: "Sri Lanka", code: "LK" },
  { value: "Sweden", label: "Sweden", code: "SE" },
  { value: "Switzerland", label: "Switzerland", code: "CH" },
  { value: "Thailand", label: "Thailand", code: "TH" },
  { value: "Turkey", label: "Turkey", code: "TR" },
  { value: "Ukraine", label: "Ukraine", code: "UA" },
  { value: "United Arab Emirates", label: "United Arab Emirates", code: "AE" },
  { value: "United Kingdom", label: "United Kingdom", code: "GB" },
  { value: "United States", label: "United States", code: "US" },
  { value: "Vietnam", label: "Vietnam", code: "VN" },
  { value: "Zambia", label: "Zambia", code: "ZM" },
  { value: "Zimbabwe", label: "Zimbabwe", code: "ZW" },
].sort((a, b) => a.label.localeCompare(b.label));
