export interface Country {
  value: string;
  label: string;
  code: string;
}

export const COUNTRIES: Country[] = [
  { value: "AF", label: "Afghanistan", code: "AF" },
  { value: "AL", label: "Albania", code: "AL" },
  { value: "DZ", label: "Algeria", code: "DZ" },
  { value: "AS", label: "American Samoa", code: "AS" },
  { value: "AD", label: "Andorra", code: "AD" },
  { value: "AO", label: "Angola", code: "AO" },
  { value: "AI", label: "Anguilla", code: "AI" },
  { value: "AQ", label: "Antarctica", code: "AQ" },
  { value: "AG", label: "Antigua and Barbuda", code: "AG" },
  { value: "AR", label: "Argentina", code: "AR" },
  { value: "AM", label: "Armenia", code: "AM" },
  { value: "AW", label: "Aruba", code: "AW" },
  { value: "AU", label: "Australia", code: "AU" },
  { value: "AT", label: "Austria", code: "AT" },
  { value: "AZ", label: "Azerbaijan", code: "AZ" },
  { value: "BS", label: "Bahamas", code: "BS" },
  { value: "BH", label: "Bahrain", code: "BH" },
  { value: "BD", label: "Bangladesh", code: "BD" },
  { value: "BB", label: "Barbados", code: "BB" },
  { value: "BY", label: "Belarus", code: "BY" },
  { value: "BE", label: "Belgium", code: "BE" },
  { value: "BZ", label: "Belize", code: "BZ" },
  { value: "BJ", label: "Benin", code: "BJ" },
  { value: "BM", label: "Bermuda", code: "BM" },
  { value: "BT", label: "Bhutan", code: "BT" },
  { value: "BO", label: "Bolivia", code: "BO" },
  { value: "BA", label: "Bosnia and Herzegovina", code: "BA" },
  { value: "BW", label: "Botswana", code: "BW" },
  { value: "BR", label: "Brazil", code: "BR" },
  { value: "IO", label: "British Indian Ocean Territory", code: "IO" },
  { value: "VG", label: "British Virgin Islands", code: "VG" },
  { value: "BN", label: "Brunei", code: "BN" },
  { value: "BG", label: "Bulgaria", code: "BG" },
  { value: "BF", label: "Burkina Faso", code: "BF" },
  { value: "BI", label: "Burundi", code: "BI" },
  { value: "KH", label: "Cambodia", code: "KH" },
  { value: "CM", label: "Cameroon", code: "CM" },
  { value: "CA", label: "Canada", code: "CA" },
  { value: "CV", label: "Cape Verde", code: "CV" },
  { value: "KY", label: "Cayman Islands", code: "KY" },
  { value: "CF", label: "Central African Republic", code: "CF" },
  { value: "TD", label: "Chad", code: "TD" },
  { value: "CL", label: "Chile", code: "CL" },
  { value: "CN", label: "China", code: "CN" },
  { value: "CX", label: "Christmas Island", code: "CX" },
  { value: "CC", label: "Cocos Islands", code: "CC" },
  { value: "CO", label: "Colombia", code: "CO" },
  { value: "KM", label: "Comoros", code: "KM" },
  { value: "CK", label: "Cook Islands", code: "CK" },
  { value: "CR", label: "Costa Rica", code: "CR" },
  { value: "HR", label: "Croatia", code: "HR" },
  { value: "CU", label: "Cuba", code: "CU" },
  { value: "CW", label: "Curaçao", code: "CW" },
  { value: "CY", label: "Cyprus", code: "CY" },
  { value: "CZ", label: "Czech Republic", code: "CZ" },
  { value: "CD", label: "Democratic Republic of the Congo", code: "CD" },
  { value: "DK", label: "Denmark", code: "DK" },
  { value: "DJ", label: "Djibouti", code: "DJ" },
  { value: "DM", label: "Dominica", code: "DM" },
  { value: "DO", label: "Dominican Republic", code: "DO" },
  { value: "TL", label: "East Timor", code: "TL" },
  { value: "EC", label: "Ecuador", code: "EC" },
  { value: "EG", label: "Egypt", code: "EG" },
  { value: "SV", label: "El Salvador", code: "SV" },
  { value: "GQ", label: "Equatorial Guinea", code: "GQ" },
  { value: "ER", label: "Eritrea", code: "ER" },
  { value: "EE", label: "Estonia", code: "EE" },
  { value: "ET", label: "Ethiopia", code: "ET" },
  { value: "FK", label: "Falkland Islands", code: "FK" },
  { value: "FO", label: "Faroe Islands", code: "FO" },
  { value: "FJ", label: "Fiji", code: "FJ" },
  { value: "FI", label: "Finland", code: "FI" },
  { value: "FR", label: "France", code: "FR" },
  { value: "PF", label: "French Polynesia", code: "PF" },
  { value: "GA", label: "Gabon", code: "GA" },
  { value: "GM", label: "Gambia", code: "GM" },
  { value: "GE", label: "Georgia", code: "GE" },
  { value: "DE", label: "Germany", code: "DE" },
  { value: "GH", label: "Ghana", code: "GH" },
  { value: "GI", label: "Gibraltar", code: "GI" },
  { value: "GR", label: "Greece", code: "GR" },
  { value: "GL", label: "Greenland", code: "GL" },
  { value: "GD", label: "Grenada", code: "GD" },
  { value: "GU", label: "Guam", code: "GU" },
  { value: "GT", label: "Guatemala", code: "GT" },
  { value: "GG", label: "Guernsey", code: "GG" },
  { value: "GN", label: "Guinea", code: "GN" },
  { value: "GW", label: "Guinea-Bissau", code: "GW" },
  { value: "GY", label: "Guyana", code: "GY" },
  { value: "HT", label: "Haiti", code: "HT" },
  { value: "HN", label: "Honduras", code: "HN" },
  { value: "HK", label: "Hong Kong", code: "HK" },
  { value: "HU", label: "Hungary", code: "HU" },
  { value: "IS", label: "Iceland", code: "IS" },
  { value: "IN", label: "India", code: "IN" },
  { value: "ID", label: "Indonesia", code: "ID" },
  { value: "IR", label: "Iran", code: "IR" },
  { value: "IQ", label: "Iraq", code: "IQ" },
  { value: "IE", label: "Ireland", code: "IE" },
  { value: "IM", label: "Isle of Man", code: "IM" },
  { value: "IL", label: "Israel", code: "IL" },
  { value: "IT", label: "Italy", code: "IT" },
  { value: "CI", label: "Ivory Coast", code: "CI" },
  { value: "JM", label: "Jamaica", code: "JM" },
  { value: "JP", label: "Japan", code: "JP" },
  { value: "JE", label: "Jersey", code: "JE" },
  { value: "JO", label: "Jordan", code: "JO" },
  { value: "KZ", label: "Kazakhstan", code: "KZ" },
  { value: "KE", label: "Kenya", code: "KE" },
  { value: "KI", label: "Kiribati", code: "KI" },
  { value: "XK", label: "Kosovo", code: "XK" },
  { value: "KW", label: "Kuwait", code: "KW" },
  { value: "KG", label: "Kyrgyzstan", code: "KG" },
  { value: "LA", label: "Laos", code: "LA" },
  { value: "LV", label: "Latvia", code: "LV" },
  { value: "LB", label: "Lebanon", code: "LB" },
  { value: "LS", label: "Lesotho", code: "LS" },
  { value: "LR", label: "Liberia", code: "LR" },
  { value: "LY", label: "Libya", code: "LY" },
  { value: "LI", label: "Liechtenstein", code: "LI" },
  { value: "LT", label: "Lithuania", code: "LT" },
  { value: "LU", label: "Luxembourg", code: "LU" },
  { value: "MO", label: "Macau", code: "MO" },
  { value: "MK", label: "Macedonia", code: "MK" },
  { value: "MG", label: "Madagascar", code: "MG" },
  { value: "MW", label: "Malawi", code: "MW" },
  { value: "MY", label: "Malaysia", code: "MY" },
  { value: "MV", label: "Maldives", code: "MV" },
  { value: "ML", label: "Mali", code: "ML" },
  { value: "MT", label: "Malta", code: "MT" },
  { value: "MH", label: "Marshall Islands", code: "MH" },
  { value: "MR", label: "Mauritania", code: "MR" },
  { value: "MU", label: "Mauritius", code: "MU" },
  { value: "YT", label: "Mayotte", code: "YT" },
  { value: "MX", label: "Mexico", code: "MX" },
  { value: "FM", label: "Micronesia", code: "FM" },
  { value: "MD", label: "Moldova", code: "MD" },
  { value: "MC", label: "Monaco", code: "MC" },
  { value: "MN", label: "Mongolia", code: "MN" },
  { value: "ME", label: "Montenegro", code: "ME" },
  { value: "MS", label: "Montserrat", code: "MS" },
  { value: "MA", label: "Morocco", code: "MA" },
  { value: "MZ", label: "Mozambique", code: "MZ" },
  { value: "MM", label: "Myanmar", code: "MM" },
  { value: "NA", label: "Namibia", code: "NA" },
  { value: "NR", label: "Nauru", code: "NR" },
  { value: "NP", label: "Nepal", code: "NP" },
  { value: "NL", label: "Netherlands", code: "NL" },
  { value: "NC", label: "New Caledonia", code: "NC" },
  { value: "NZ", label: "New Zealand", code: "NZ" },
  { value: "NI", label: "Nicaragua", code: "NI" },
  { value: "NE", label: "Niger", code: "NE" },
  { value: "NG", label: "Nigeria", code: "NG" },
  { value: "NU", label: "Niue", code: "NU" },
  { value: "NF", label: "Norfolk Island", code: "NF" },
  { value: "KP", label: "North Korea", code: "KP" },
  { value: "MP", label: "Northern Mariana Islands", code: "MP" },
  { value: "NO", label: "Norway", code: "NO" },
  { value: "OM", label: "Oman", code: "OM" },
  { value: "PK", label: "Pakistan", code: "PK" },
  { value: "PW", label: "Palau", code: "PW" },
  { value: "PS", label: "Palestine", code: "PS" },
  { value: "PA", label: "Panama", code: "PA" },
  { value: "PG", label: "Papua New Guinea", code: "PG" },
  { value: "PY", label: "Paraguay", code: "PY" },
  { value: "PE", label: "Peru", code: "PE" },
  { value: "PH", label: "Philippines", code: "PH" },
  { value: "PN", label: "Pitcairn", code: "PN" },
  { value: "PL", label: "Poland", code: "PL" },
  { value: "PT", label: "Portugal", code: "PT" },
  { value: "PR", label: "Puerto Rico", code: "PR" },
  { value: "QA", label: "Qatar", code: "QA" },
  { value: "CG", label: "Republic of the Congo", code: "CG" },
  { value: "RE", label: "Réunion", code: "RE" },
  { value: "RO", label: "Romania", code: "RO" },
  { value: "RU", label: "Russia", code: "RU" },
  { value: "RW", label: "Rwanda", code: "RW" },
  { value: "BL", label: "Saint Barthélemy", code: "BL" },
  { value: "SH", label: "Saint Helena", code: "SH" },
  { value: "KN", label: "Saint Kitts and Nevis", code: "KN" },
  { value: "LC", label: "Saint Lucia", code: "LC" },
  { value: "MF", label: "Saint Martin", code: "MF" },
  { value: "PM", label: "Saint Pierre and Miquelon", code: "PM" },
  { value: "VC", label: "Saint Vincent and the Grenadines", code: "VC" },
  { value: "WS", label: "Samoa", code: "WS" },
  { value: "SM", label: "San Marino", code: "SM" },
  { value: "ST", label: "São Tomé and Príncipe", code: "ST" },
  { value: "SA", label: "Saudi Arabia", code: "SA" },
  { value: "SN", label: "Senegal", code: "SN" },
  { value: "RS", label: "Serbia", code: "RS" },
  { value: "SC", label: "Seychelles", code: "SC" },
  { value: "SL", label: "Sierra Leone", code: "SL" },
  { value: "SG", label: "Singapore", code: "SG" },
  { value: "SX", label: "Sint Maarten", code: "SX" },
  { value: "SK", label: "Slovakia", code: "SK" },
  { value: "SI", label: "Slovenia", code: "SI" },
  { value: "SB", label: "Solomon Islands", code: "SB" },
  { value: "SO", label: "Somalia", code: "SO" },
  { value: "ZA", label: "South Africa", code: "ZA" },
  { value: "KR", label: "South Korea", code: "KR" },
  { value: "SS", label: "South Sudan", code: "SS" },
  { value: "ES", label: "Spain", code: "ES" },
  { value: "LK", label: "Sri Lanka", code: "LK" },
  { value: "SD", label: "Sudan", code: "SD" },
  { value: "SR", label: "Suriname", code: "SR" },
  { value: "SJ", label: "Svalbard and Jan Mayen", code: "SJ" },
  { value: "SZ", label: "Swaziland", code: "SZ" },
  { value: "SE", label: "Sweden", code: "SE" },
  { value: "CH", label: "Switzerland", code: "CH" },
  { value: "SY", label: "Syria", code: "SY" },
  { value: "TW", label: "Taiwan", code: "TW" },
  { value: "TJ", label: "Tajikistan", code: "TJ" },
  { value: "TZ", label: "Tanzania", code: "TZ" },
  { value: "TH", label: "Thailand", code: "TH" },
  { value: "TG", label: "Togo", code: "TG" },
  { value: "TK", label: "Tokelau", code: "TK" },
  { value: "TO", label: "Tonga", code: "TO" },
  { value: "TT", label: "Trinidad and Tobago", code: "TT" },
  { value: "TN", label: "Tunisia", code: "TN" },
  { value: "TR", label: "Turkey", code: "TR" },
  { value: "TM", label: "Turkmenistan", code: "TM" },
  { value: "TC", label: "Turks and Caicos Islands", code: "TC" },
  { value: "TV", label: "Tuvalu", code: "TV" },
  { value: "VI", label: "U.S. Virgin Islands", code: "VI" },
  { value: "UG", label: "Uganda", code: "UG" },
  { value: "UA", label: "Ukraine", code: "UA" },
  { value: "AE", label: "United Arab Emirates", code: "AE" },
  { value: "GB", label: "United Kingdom", code: "GB" },
  { value: "US", label: "United States", code: "US" },
  { value: "UY", label: "Uruguay", code: "UY" },
  { value: "UZ", label: "Uzbekistan", code: "UZ" },
  { value: "VU", label: "Vanuatu", code: "VU" },
  { value: "VA", label: "Vatican", code: "VA" },
  { value: "VE", label: "Venezuela", code: "VE" },
  { value: "VN", label: "Vietnam", code: "VN" },
  { value: "WF", label: "Wallis and Futuna", code: "WF" },
  { value: "EH", label: "Western Sahara", code: "EH" },
  { value: "YE", label: "Yemen", code: "YE" },
  { value: "ZM", label: "Zambia", code: "ZM" },
  { value: "ZW", label: "Zimbabwe", code: "ZW" },
].sort((a, b) => a.label.localeCompare(b.label));
