-- Migration: Add extra profile and invoice fields to companies table
-- Date: 2026-08-04

ALTER TABLE public.companies
ADD COLUMN IF NOT EXISTS email VARCHAR(255),
ADD COLUMN IF NOT EXISTS phone VARCHAR(255),
ADD COLUMN IF NOT EXISTS address VARCHAR(1000),
ADD COLUMN IF NOT EXISTS postal_code VARCHAR(100),
ADD COLUMN IF NOT EXISTS country VARCHAR(100),
ADD COLUMN IF NOT EXISTS city VARCHAR(255),
ADD COLUMN IF NOT EXISTS state VARCHAR(255),
ADD COLUMN IF NOT EXISTS invoice_address VARCHAR(1000),
ADD COLUMN IF NOT EXISTS invoice_city VARCHAR(255),
ADD COLUMN IF NOT EXISTS invoice_postal_code VARCHAR(100),
ADD COLUMN IF NOT EXISTS invoice_state VARCHAR(255);
